### ISSUE TITLE
error installing

### ISSUE THREAD

**Issue by ccorcos** [gruntjs/grunt-contrib-sass#210]
```
~/p/grunt ❯❯❯ npm install grunt-contrib-scss --save-dev
npm WARN package.json grunt-utils@1.0.0 No description
npm WARN package.json grunt-utils@1.0.0 No repository field.
npm WARN package.json grunt-utils@1.0.0 No README data
npm WARN package.json grunt-utils@1.0.0 No license field.
-
> node-sass@0.7.0 install /Users/chetcorcos/playground/grunt/node_modules/grunt-contrib-scss/node_modules/node-sass
> node build.js

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/binding/binding.o
In file included from ../binding.cpp:7:
../sass_context_wrapper.h:10:3: error: unknown type name 'uv_work_t'
  uv_work_t request;
  ^
../sass_context_wrapper.h:20:3: error: unknown type name 'uv_work_t'
  uv_work_t request;
  ^
../binding.cpp:13:20: error: unknown type name 'uv_work_t'
void WorkOnContext(uv_work_t* req) {
                   ^
../binding.cpp:19:22: error: unknown type name 'uv_work_t'
void MakeOldCallback(uv_work_t* req) {
                     ^
../binding.cpp:20:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/Users/chetcorcos/.node-gyp/0.12.7/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../binding.cpp:29:31: error: no matching function for call to 'Null'
            Local<Value>::New(Null()),
                              ^~~~
/Users/chetcorcos/.node-gyp/0.12.7/deps/v8/include/v8.h:6604:19: note: candidate function not
      viable: requires single argument 'isolate', but no arguments were provided
Handle<Primitive> Null(Isolate* isolate) {
                  ^
../binding.cpp:30:39: error: no member named 'New' in 'v8::String'
            Local<Value>::New(String::New(ctx->output_string))
                              ~~~~~~~~^
../binding.cpp:33:24: error: member reference type 'v8::Persistent<v8::Function>' is not a
      pointer; maybe you meant to use '.'?
        ctx_w->callback->Call(Context::GetCurrent()->Global(), argc, argv);
        ~~~~~~~~~~~~~~~^~
                       .
../binding.cpp:33:26: error: no member named 'Call' in 'v8::Persistent<v8::Function,
      v8::NonCopyablePersistentTraits<v8::Function> >'
        ctx_w->callback->Call(Context::GetCurrent()->Global(), argc, argv);
        ~~~~~~~~~~~~~~~  ^
../binding.cpp:33:40: error: no member named 'GetCurrent' in 'v8::Context'
        ctx_w->callback->Call(Context::GetCurrent()->Global(), argc, argv);
                              ~~~~~~~~~^
../binding.cpp:38:39: error: no member named 'New' in 'v8::String'
            Local<Value>::New(String::New(ctx->error_message))
                              ~~~~~~~~^
../binding.cpp:41:24: error: member reference type 'v8::Persistent<v8::Function>' is not a
      pointer; maybe you meant to use '.'?
        ctx_w->callback->Call(Context::GetCurrent()->Global(), argc, argv);
        ~~~~~~~~~~~~~~~^~
                       .
../binding.cpp:41:26: error: no member named 'Call' in 'v8::Persistent<v8::Function,
      v8::NonCopyablePersistentTraits<v8::Function> >'
        ctx_w->callback->Call(Context::GetCurrent()->Global(), argc, argv);
        ~~~~~~~~~~~~~~~  ^
../binding.cpp:41:40: error: no member named 'GetCurrent' in 'v8::Context'
        ctx_w->callback->Call(Context::GetCurrent()->Global(), argc, argv);
                              ~~~~~~~~~^
../binding.cpp:50:31: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
Handle<Value> OldRender(const Arguments& args) {
                              ^~~~~~~~~
                              v8::internal::Arguments
/Users/chetcorcos/.node-gyp/0.12.7/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments'
      declared here
class Arguments;
      ^
../binding.cpp:51:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/Users/chetcorcos/.node-gyp/0.12.7/deps/v8/include/v8.h:816:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../binding.cpp:55:13: error: no member named 'AsciiValue' in 'v8::String'
    String::AsciiValue astr(args[0]);
    ~~~~~~~~^
../binding.cpp:56:58: error: type 'const v8::internal::Arguments' does not provide a subscript
      operator
    Local<Function> callback = Local<Function>::Cast(args[1]);
                                                     ~~~~^~
../binding.cpp:57:13: error: no member named 'AsciiValue' in 'v8::String'
    String::AsciiValue bstr(args[2]);
    ~~~~~~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/binding/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/chetcorcos/playground/grunt/node_modules/grunt-contrib-scss/node_modules/node-sass
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
Build failed
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "grunt-contrib-scss" "--save-dev"
npm ERR! node v0.12.7
npm ERR! npm  v2.12.1
npm ERR! code ELIFECYCLE

npm ERR! node-sass@0.7.0 install: `node build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@0.7.0 install script 'node build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/chetcorcos/playground/grunt/npm-debug.log
```

**Comment by sindresorhus** [comment]
This isn't `grunt-contrib-scss`.
